import { useEffect, useState } from 'react';
import { useData } from '../../data/DataContext';
import { useRole } from '../../state/Role';
import { useToast } from '../../components/Toast';
import { ChainStatus, ChainControls } from '../../components/ApptChainControls';
import { formatMoney } from '../../domain/money';
import { isCentralMaterial } from '../../domain/apptchain';
import type { SupplierBill, PurchaseOrder, Crv, Subcontractor } from '../../data/types';

/**
 * Supplier bills (spec §6): generated from CRVs against POs, priced at material
 * master rates. Central materials (Cement/Steel/Bitumen) route the CFO ladder;
 * local materials route the PD ladder. Pre-Audit sits on both.
 */
export function SupplierBillsTab({ projectId }: { projectId: string }) {
  const { provider } = useData();
  const { role, user } = useRole();
  const { toast } = useToast();
  const [bills, setBills] = useState<SupplierBill[]>([]);
  const [pos, setPos] = useState<PurchaseOrder[]>([]);
  const [crvs, setCrvs] = useState<Crv[]>([]);
  const [subs, setSubs] = useState<Subcontractor[]>([]);
  const [chosen, setChosen] = useState<Set<string>>(new Set());

  const by = user?.name ?? role;
  const mayGenerate = role === 'admin' || user?.appointmentId === 'proc_engr';

  async function load() {
    const [b, p, c, s] = await Promise.all([
      provider.listSupplierBills(projectId), provider.listPurchaseOrders(projectId),
      provider.listCrvs(projectId), provider.listSubcontractors(projectId),
    ]);
    setBills(b); setPos(p); setCrvs(c); setSubs(s);
  }
  useEffect(() => { void load(); /* eslint-disable-next-line */ }, [provider, projectId]);

  const supplierName = (id: string) => subs.find((s) => s.id === id)?.name ?? id;
  const posWithCrv = pos.filter((p) => crvs.some((c) => c.poId === p.id));

  function toggle(poId: string) {
    setChosen((prev) => { const n = new Set(prev); n.has(poId) ? n.delete(poId) : n.add(poId); return n; });
  }

  async function generate() {
    if (chosen.size === 0) return;
    const bill = await provider.generateSupplierBillFromCrvs(projectId, [...chosen], by);
    setChosen(new Set());
    await load();
    toast({ message: `Bill ${bill.billNo} generated (${bill.kind}) — routes to ${bill.kind === 'central' ? 'CFO' : 'PD'}`, kind: 'success' });
  }

  function patch(updated: SupplierBill) {
    setBills((prev) => prev.map((b) => (b.id === updated.id ? updated : b)));
  }

  return (
    <div className="stack-lg">
      <section className="card">
        <div className="section-head"><h3>Generate supplier bill from CRVs</h3>
          <span className="muted small">bill = Σ CRV received qty × master rate · central materials (Cement/Steel/Bitumen) route the CFO ladder</span>
        </div>
        {!mayGenerate ? (
          <p className="muted small">Generated by the Procurement Engineer.</p>
        ) : posWithCrv.length === 0 ? (
          <p className="muted small">No POs with CRVs yet — receive material at store first.</p>
        ) : (
          <div className="create-row" style={{ flexWrap: 'wrap' }}>
            {posWithCrv.map((p) => (
              <label key={p.id} className="small" style={{ marginRight: 12 }}>
                <input type="checkbox" checked={chosen.has(p.id)} onChange={() => toggle(p.id)} /> {p.poNo} · {supplierName(p.supplierId)}
              </label>
            ))}
            <button className="btn" aria-label="Generate supplier bill" disabled={chosen.size === 0} onClick={generate}>Generate bill</button>
          </div>
        )}
      </section>

      <section className="card">
        <div className="section-head"><h3>Supplier bills</h3></div>
        {bills.length === 0 ? (
          <p className="muted small">No supplier bills yet.</p>
        ) : (
          <table className="data-table" aria-label="Supplier bills">
            <thead><tr><th>Bill</th><th>Supplier</th><th>Class</th><th className="num">Amount</th><th>Status / chain</th><th></th></tr></thead>
            <tbody>
              {bills.map((b) => (
                <tr key={b.id}>
                  <td className="mono small">{b.billNo}<div className="muted small">{b.lines.length} material{b.lines.length === 1 ? '' : 's'}</div></td>
                  <td className="small">{supplierName(b.supplierId)}</td>
                  <td>
                    <span className={`status-pill ${b.kind === 'central' ? 'st-open' : 'st-ack'}`}>{b.kind}</span>
                    {b.lines.some((l) => isCentralMaterial(l.materialCode)) && <div className="muted small">→ CFO</div>}
                  </td>
                  <td className="num">{formatMoney(b.amount)}</td>
                  <td>
                    <span className={`status-pill st-${b.status === 'paid' ? 'resolved' : b.status === 'in_chain' ? 'ack' : 'open'}`}>{b.status.replace('_', ' ')}</span>
                    <ChainStatus chain={b.chain} refNo={b.billNo} />
                  </td>
                  <td>
                    {!b.chain && b.status === 'draft' && (
                      <button className="btn btn-mini" aria-label={`Submit ${b.billNo}`}
                        onClick={async () => patch(await provider.submitSupplierBill(projectId, b.id, by))}>Submit for approval</button>
                    )}
                    <ChainControls chain={b.chain} refNo={b.billNo} me={user?.appointmentId} isAdmin={role === 'admin'}
                      canResubmit={['proc_engr', 'spm']}
                      onAct={async () => patch(await provider.actOnSupplierBill(projectId, b.id, by))}
                      onReturn={async (rm) => patch(await provider.returnSupplierBill(projectId, b.id, by, rm))}
                      onResubmit={async () => patch(await provider.resubmitSupplierBill(projectId, b.id, by))}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </div>
  );
}
